name: runnur
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # audioplayers: ^6.0.0
  # go_router: ^14.2.0
  logging: ^1.2.0
  # flutter_riverpod: ^2.5.1
  # shared_preferences: ^2.2.3
  very_good_analysis: ^5.1.0
  # games_services: ^4.0.1
  # google_mobile_ads: ^5.1.0
  # in_app_purchase: ^3.2.0
  flutter_launcher_icons: ^0.13.1
  flame: ^1.17.0
  flame_tiled: ^1.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true

  assets:
    - assets/tiles/
    - assets/images/HUD/
    - assets/images/Background/
    - assets/images/Items/Fruits/
    - assets/images/Terrain/Terrain (16x16).png
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/


#   fonts:
#     - family: Permanet Marker
#       fonts:
#         - asset: assets/Permanet_Marker/PermanetMarker-Regular.ttf

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon.png"
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/adaptive-icon-foreground.png"
